package com.bpc.modulesdk.errors;

/**
 * Created by Masloed on 27.12.2016.
 */


public interface ErrorCode {

    int SUCCESS = 0;
    int BAD_REQUEST = 1;
    int INTERNAL_SERVER_ERROR = 2;
    int UNSUPPORTED_OPERATION = 3;
    int INVALID_FLOW_STATE = 4;
    int INCOMPATIBLE_REVISION = 5;
    int SERVICE_UNAVAILABLE = 6;
    int DEVICE_BINDING_REQUIRED = 101;
    int DEVICE_BINDING_CONFIRMATION_EXCPECTED = 102;
    int DEVICE_BINDING_REJECTED = 103;
    int INVALID_ACCESS_TOKEN = 104;
    int INVALID_LOGIN_PASSWORD = 105;
    int USER_IS_LOCKED = 106;
    int PARAMS_CONFIRMATION_REQUIRED = 107;
    int OPERATION_CONFIRMATION_REQUIRED = 108;
    int ADDITIONAL_PARAMS_REQUIRED = 109;
    int INCORRECT_SECURITY_CARD = 110;
    int NOT_ENOUGH_MONEY = 111;
    int NO_LOCATION_PROVIDED = 112;
    int LOCATION_IS_RESTRICTED = 113;

    int MAXIMUM_BINDED_DEVICE_NUMBER_REACHED = 117;
    int PASSWORD_CHANGE_EXPECTED = 118;
    int INVALID_PASSWORD_PROVIDED = 119;
    int INCORRECT_SUB_AGENT_PROVIDED = 121;

    int INVALID_CARD_STATUS = 209;
    int CARD_ALREADY_EXISTS = 210;

    int TRANSACTION_LIMIT_EXCEEDED = 1115;
    int PHOTO_IS_MANDATORY = 1116;

}
